# Generated by Django 4.2.30 on 2026-07-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactuslead_newslettersubscriber_uiinteractionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('financial_segment', models.CharField(choices=[('Personal Loans', 'Personal Loan'), ('Business Financing', 'Business Loan'), ('Credit Card Solutions', 'Credit Card & Debt Consolidation'), ('Mortgages', 'Mortgage')], max_length=100)),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Consultation Lead',
                'verbose_name_plural': 'Consultation Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnquiryLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Enquiry Lead',
                'verbose_name_plural': 'Enquiry Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
