# Generated by Django 4.2.30 on 2026-07-11 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_consultationlead_enquirylead'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUsLead',
        ),
    ]
