# Generated by Django 4.2.30 on 2026-07-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_contactuslead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationlead',
            name='financial_segment',
            field=models.CharField(choices=[('Personal Loan', 'Personal Loan'), ('Business Loan', 'Business Loan'), ('Business Account', 'Business Account'), ('Mortgage', 'Mortgage'), ('Credit Card', 'Credit Card')], max_length=100),
        ),
    ]
